# Generated by Django 4.2.13 on 2024-07-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_code', models.CharField(max_length=100, unique=True)),
                ('terminal_branch', models.CharField(max_length=255)),
                ('down_date', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
                ('atm_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM_MGNT.brand')),
                ('down_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM_MGNT.downreason')),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_code', models.CharField(max_length=100, unique=True)),
                ('terminal_branch', models.CharField(max_length=255)),
                ('atm_ip', models.CharField(max_length=100)),
                ('atm_acc_no', models.CharField(max_length=50, unique=True)),
                ('branch_code', models.CharField(max_length=50)),
                ('atm_user', models.CharField(max_length=100)),
                ('atm_password', models.CharField(max_length=100)),
                ('atm_ram', models.CharField(max_length=50)),
                ('atm_storage', models.CharField(max_length=50)),
                ('atm_os', models.CharField(max_length=50)),
                ('atm_bit', models.CharField(max_length=10)),
                ('atm_p', models.CharField(max_length=50)),
                ('atm_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM_MGNT.brand')),
            ],
        ),
    ]
