# Generated by Django 4.2.13 on 2024-07-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM_MGNT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdown',
            name='terminal_code',
            field=models.CharField(max_length=100),
        ),
    ]
