# Generated by Django 4.2.13 on 2024-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM_MGNT', '0002_alter_atmdown_terminal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdown',
            name='down_reason',
            field=models.CharField(max_length=200),
        ),
    ]
