# Generated by Django 4.2.13 on 2024-09-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM_MGNT', '0004_alter_atmdown_atm_brand_alter_atmdown_down_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='atm_bit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_p',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='atm_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
