# Generated by Django 4.2.13 on 2024-09-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM_MGNT', '0005_alter_atm_atm_bit_alter_atm_atm_os_alter_atm_atm_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='atm_p',
        ),
    ]
