services:
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: atm_mgmt
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: P@ssword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 10
    restart: always
    volumes:
      - /var/backup/atm_support:/var/lib/postgresql/data
    networks:
      - application

  migration:
    image: atm_mgmt:latest
    profiles: [initialize]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    networks:
      - application

  app:
    image: atm_mgmt:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "172.16.15.131:8001:8000"
    env_file:
      - .env
    restart: always
    networks:
      - application
    volumes:
      - .:/app

networks:
  application:
