services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: atm_mgmt
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: P@ssword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - application

  migration:
    image: devtest:latest
    profiles: [initialize]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    networks:
      - application

  app:
    image: devtest:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "192.168.10.6:8000:8000"
    env_file:
      - .env
    networks:
      - application
    volumes:
      - .:/app

networks:
  application:
